// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset.sql

package database

import (
	"context"
)

const reset = `-- name: Reset :execrows
DELETE FROM users
`

// noinspection SqlWithoutWhere
func (q *Queries) Reset(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, reset)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
